Repository library-angels/code-library-backend, pull requests merged in 2020-11, with the labels that each got.

#117 Add unique roles migration for identity microservice
  identity/migrations/2020-11-02-210000_add_unique_roles/down.sql
  identity/migrations/2020-11-02-210000_add_unique_roles/up.sql
Labels: bug

#122 Helpers: Add `enum Error`
  Cargo.lock
  book/src/db/models.rs
  helpers/Cargo.toml
  helpers/src/lib.rs
  helpers/src/rpc.rs
  identity/src/rpc/service.rs
Labels: feature

#123 book: Restructure lib
  book/src/db/models.rs
  book/src/lib.rs
  book/src/rpc/mod.rs
  book/src/rpc/models.rs
  book/src/rpc/server.rs
  book/src/rpc/service.rs
Labels: feature

#125 api::rpc: Simplify `fn identity_client()`
  api/src/rpc.rs
Labels: feature

#126 CD (api): add `libpq` to final image
  api/Dockerfile
Labels: bug, cicd

#131 `book::db::queries`: simplify `fn get_book_by_id`
  book/src/db/queries.rs
Labels: refactor

#133 `cargo update`
  Cargo.lock
Labels: dependencies

#136 `book`: alter series relation
  book/migrations/2020-11-11-161454_alter_series/down.sql
  book/migrations/2020-11-11-161454_alter_series/up.sql
  book/src/db/models.rs
  book/src/db/queries.rs
  book/src/db/schema.rs
Labels: database, feature

#137 `book`: make series optional
  book/src/db/queries.rs
  book/src/rpc/models.rs
Labels: fix

#139 `book::main`: Fix log-level of address-logging
  book/src/main.rs
Labels: fix

#120 CI: Set up postgres service container for tests
  .github/workflows/ci.yml
Labels: cicd, database, feature

#143 CI: Run on pull_request
  .github/workflows/ci.yml
Labels: cicd, fix

#140 CI: Run doc tests
  .github/workflows/ci.yml
Labels: cicd, documentation, feature

#146 `api::rpc`: Rm redundant closures
  api/src/rpc.rs
Labels: refactor

#134 Adds database pagination module to helpers crate
  helpers/src/db/mod.rs
  helpers/src/db/pagination.rs
  helpers/src/rpc.rs
Labels: feature

#147 CI: Simplify strategy matrix
  .github/workflows/ci.yml
Labels: cicd, refactor

#151 Implement `GET /book/?page={u32}[&page_size={u32}]`
  api/src/endpoints/book.rs
  api/src/router.rs
  book/src/db/queries.rs
  book/src/rpc/models.rs
  book/src/rpc/server.rs
  book/src/rpc/service.rs
Labels: feature

#148 CD: Unify jobs
  .github/workflows/cd-dev-api.yml
  .github/workflows/cd-dev-book.yml
  .github/workflows/cd-dev-borrow.yml
  .github/workflows/cd-dev-identity.yml
  .github/workflows/cd-dev-notification.yml
Labels: cicd, refactor

#156 `book::db::queries`: Document queries with SQL
  book/src/db/queries.rs
Labels: database, documentation

#155 Identity server refactor to binary and library
  Cargo.lock
  api/Cargo.toml
  api/src/endpoints/identity.rs
  api/src/rpc.rs
  identity/Cargo.toml
  identity/src/db/mod.rs
  identity/src/lib/authentication/mod.rs
  identity/src/lib/authentication/oauth.rs
  identity/src/lib/config.rs
  identity/src/lib/db/mod.rs
  identity/src/lib/db/models.rs
  identity/src/lib/db/schema.rs
  identity/src/lib/lib.rs
  identity/src/lib/rpc/mod.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/rpc/service.rs
  identity/src/lib/session/jwt.rs
  identity/src/lib/session/mod.rs
  identity/src/main.rs
Labels: refactor

#158 Updates imports in identity service according to new import schema
  identity/src/lib/config.rs
  identity/src/lib/db/mod.rs
  identity/src/lib/db/models.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/session/jwt.rs
  identity/src/main.rs
Labels: refactor

#159 Removes global static configuration and database from identity service
  identity/src/lib/config.rs
  identity/src/lib/db/mod.rs
  identity/src/lib/rpc/server.rs
  identity/src/main.rs
Labels: refactor

#157 `api::endpoints::book`: Make query param `page` optional
  api/src/endpoints/book.rs
Labels: feature

#160 openapi: add book list
  api/openapi.yml
Labels: documentation

#162 Security concept
  README.md
  SECURITY.md
Labels: documentation

#164 Fix schema file path
  book/diesel.toml
  identity/diesel.toml
Labels: fix

#169 `book::db::models`: Fix attribute order of `Language`
  book/src/lib/db/models.rs
Labels: fix

#168 `cargo update`
  Cargo.lock
Labels: dependencies
