Repository library-angels/code-library-backend, pull requests merged in 2020-10, with the labels that each got.

#91 cargo update
  Cargo.lock
Labels: feature

#93 Add Cargo.lock to continuous delivery pipeline
  .github/workflows/cd-dev-api.yml
  .github/workflows/cd-dev-book.yml
  .github/workflows/cd-dev-borrow.yml
  .github/workflows/cd-dev-identity.yml
  .github/workflows/cd-dev-notification.yml
Labels: CI/CD

#94 api: Drop unused endpoint documentation
  api/REST-API.md
Labels: documentation

#103 Make default microservice server ports unique
  book/src/config.rs
  borrow/src/config.rs
  notification/src/config.rs
Labels: feature

#106 Changes the channel limit per ip for the identity microservice
  identity/src/main.rs
Labels: bug
