Repository library-angels/code-library-backend, pull requests merged in 2020-05, with the labels that each got.

#27 Tests - Cleanup - CI set up
  .circleci/config.yml
  Cargo.lock
  api/diesel.toml
  api/migrations/.gitkeep
  api/migrations/00000000000000_diesel_initial_setup/down.sql
  api/migrations/00000000000000_diesel_initial_setup/up.sql
  api/src/config.rs
  api/src/db/db_connection.rs
  api/src/db/db_model.rs
  api/src/db/helpers/book_endpoint.rs
  api/src/db/helpers/mod.rs
  api/src/db/mod.rs
  api/src/db/tests/db.sql
  api/src/db/tests/db_tests.rs
  api/src/db/tests/mod.rs
  api/src/db/tests/test_db_connection.rs
  api/src/endpoints/book.rs
  api/src/endpoints/borrow.rs
  api/src/endpoints/identity.rs
  api/src/endpoints/mod.rs
  api/src/endpoints/notification.rs
  api/src/endpoints/root.rs
  api/src/lib.rs
  api/src/main.rs
  api/src/query_models/book.rs
  api/src/query_models/mod.rs
  api/src/query_models/publisher.rs
  api/src/router.rs
  api/tests/book_endpoint_tests.rs
  tests/test.rs
Labels: feature

#29 Feature get books with designationid with tests
  api/src/db/helpers/book_endpoint.rs
  api/src/db/tests/db_tests.rs
  api/src/query_models/book.rs
  api/tests/book_endpoint_tests.rs
Labels: bug, feature

#32 Feature get books with designation id with tests
  api/src/db/helpers/book_endpoint.rs
  api/src/db/tests/db_tests.rs
  api/src/query_models/book.rs
  api/tests/book_endpoint_tests.rs
Labels: bug, feature

#23 Feature authentication
  api/src/endpoints/identity.rs
  api/src/main.rs
  api/src/router.rs
Labels: bug

#26 Documentation readme file
  README.md
Labels: documentation

#24 Added docker files
  api/full.Dockerfile
  api/slim.Dockerfile
  book/full.Dockerfile
  book/slim.Dockerfile
  borrow/full.Dockerfile
  borrow/slim.Dockerfile
  identity/full.Dockerfile
  identity/slim.Dockerfile
  notification/full.Dockerfile
  notification/slim.Dockerfile
Labels: feature
