Repository library-angels/code-library-backend, pull requests merged in 2020-12, with the labels that each got.

#161 Refactor/identity integration tests
  Cargo.lock
  identity/Cargo.toml
  identity/src/lib/config.rs
  identity/src/lib/db/models.rs
  identity/src/lib/rpc/mod.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/rpc/service.rs
  identity/src/main.rs
  identity/tests/rpc_endpoints.rs
  identity/tests/sample_data.rs
Labels: refactor, testing

#170 Refactor/book db conn
  book/src/config.rs
  book/src/lib/db/mod.rs
  book/src/lib/db/queries.rs
  book/src/lib/lib.rs
  book/src/lib/rpc/mod.rs
  book/src/lib/rpc/server.rs
  book/src/main.rs
Labels: refactor

#172 Move identity service rpc models into their own module
  identity/src/lib/rpc/mod.rs
  identity/src/lib/rpc/models.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/rpc/service.rs
  identity/tests/rpc_endpoints.rs
Labels: refactor

#173 Refactor/identity service initialization
  identity/src/lib/config.rs
  identity/src/lib/db/mod.rs
  identity/src/lib/rpc/mod.rs
  identity/src/lib/rpc/server.rs
  identity/src/main.rs
  identity/tests/rpc_endpoints.rs
Labels: refactor

#175 `book::rpc::models`: Restructure im- and exports
  book/src/lib/rpc/models.rs
Labels: refactor

#176 Change model datetime from SystemTime to chrono DateTime
  Cargo.lock
  identity/Cargo.toml
  identity/src/lib/db/models.rs
  identity/src/lib/rpc/server.rs
  identity/tests/sample_data.rs
Labels: refactor

#179 `book::rpc`: Provide getter for `BookServiceClient`
  api/src/rpc.rs
  book/src/lib/rpc/mod.rs
Labels: refactor

#177 `book`: Simplify models through serde magic
  book/src/lib/db/models.rs
  book/src/lib/rpc/models.rs
  book/src/lib/rpc/server.rs
Labels: refactor

#178 Refactor/identity queries module
  identity/src/lib/db/mod.rs
  identity/src/lib/db/models.rs
  identity/src/lib/db/queries.rs
  identity/src/lib/rpc/server.rs
  identity/tests/db_queries.rs
Labels: refactor

#181 Unify `type DbPool`, `type DbConn`, `fn get_db_pool` into `helpers::db`
  book/src/lib/db/mod.rs
  book/src/main.rs
  helpers/src/db/mod.rs
  helpers/src/db/pagination.rs
  identity/src/lib/db/mod.rs
Labels: refactor

#182 `api`: Refactor file structure + simplify main
  api/Cargo.toml
  api/src/lib/config.rs
  api/src/lib/endpoints/book.rs
  api/src/lib/endpoints/identity.rs
  api/src/lib/endpoints/mod.rs
  api/src/lib/endpoints/root.rs
  api/src/lib/lib.rs
  api/src/lib/middleware.rs
  api/src/lib/response.rs
  api/src/lib/router.rs
  api/src/lib/rpc.rs
  api/src/main.rs
Labels: refactor

#186 Makes tests respect preset environment variables
  identity/tests/rpc_endpoints.rs
Labels: refactor

#187 Identity session jwt module refactoring
  identity/src/lib/rpc/models.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/session/jwt.rs
  identity/tests/rpc_endpoints.rs
Labels: refactor

#183 `helpers::result`: Add `type StdResult`
  helpers/src/lib.rs
  helpers/src/result.rs
Labels: feature

#180 `book:rpc`: Refactor server + server-getter
  book/src/lib/rpc/mod.rs
  book/src/lib/rpc/server.rs
  book/src/main.rs
Labels: refactor

#185 `book::models`: Expose `RawBook`
  book/src/lib/db/models.rs
  book/src/lib/rpc/models.rs
Labels: feature

#184 api: Make configuration server-local
  api/src/config.rs
  api/src/lib/config.rs
  api/src/lib/endpoints/book.rs
  api/src/lib/endpoints/identity.rs
  api/src/lib/lib.rs
  api/src/lib/middleware.rs
  api/src/lib/router.rs
  api/src/lib/rpc.rs
  api/src/main.rs
Labels: refactor

#189 `book::rpc`: test `fn rpc_server`
  book/src/lib/rpc/mod.rs
Labels: testing

#188 Identity oauth refactoring
  identity/src/lib/authentication/mod.rs
  identity/src/lib/authentication/oauth.rs
  identity/src/lib/db/queries.rs
  identity/src/lib/rpc/models.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/rpc/service.rs
  identity/tests/db_queries.rs
  identity/tests/rpc_endpoints.rs
Labels: refactor

#196 `security`: Fix source in foodnote
  SECURITY.md
Labels: documentation, fix

#194 `GET /book`: specify category
  api/src/lib/endpoints/book.rs
  book/src/lib/db/queries.rs
  book/src/lib/rpc/server.rs
  book/src/lib/rpc/service.rs
Labels: feature

#197 Feature/identity simplify user roles
  identity/migrations/2020-12-09-140000_drop_users_roles/down.sql
  identity/migrations/2020-12-09-140000_drop_users_roles/up.sql
  identity/src/lib/authentication/mod.rs
  identity/src/lib/db/models.rs
  identity/src/lib/db/queries.rs
  identity/src/lib/db/schema.rs
  identity/src/lib/rpc/models.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/rpc/service.rs
  identity/tests/db_queries.rs
  identity/tests/rpc_endpoints.rs
  identity/tests/sample_data.rs
Labels: feature, refactor

#198 Feature/identity simplify roles
  identity/migrations/2020-12-09-160000_drop_role_attributes/down.sql
  identity/migrations/2020-12-09-160000_drop_role_attributes/up.sql
  identity/src/lib/db/models.rs
  identity/src/lib/db/schema.rs
  identity/src/lib/rpc/models.rs
  identity/src/lib/rpc/server.rs
  identity/tests/db_queries.rs
  identity/tests/rpc_endpoints.rs
Labels: feature, refactor

#201 Downgrades the uuid module version to 0.7
  Cargo.lock
  book/Cargo.toml
Labels: dependencies, refactor

#208 Identity service - Migrate user identifiers to UUID
  Cargo.lock
  identity/Cargo.toml
  identity/migrations/2020-12-14-110000_migrate_uuid/down.sql
  identity/migrations/2020-12-14-110000_migrate_uuid/up.sql
  identity/src/lib/authentication/mod.rs
  identity/src/lib/db/models.rs
  identity/src/lib/db/queries.rs
  identity/src/lib/db/schema.rs
  identity/src/lib/rpc/models.rs
  identity/src/lib/rpc/server.rs
  identity/src/lib/rpc/service.rs
  identity/src/lib/session/jwt.rs
  identity/tests/db_queries.rs
  identity/tests/rpc_endpoints.rs
  identity/tests/sample_data.rs
Labels: refactor

#213 Bump uuid from 0.7.4 to 0.8.1
  Cargo.lock
  book/Cargo.toml
  identity/Cargo.toml
Labels: dependencies
